apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-auth
  namespace: monitoring
data:
  slack_url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX" // "Dont have slack, so just a demo url"
